#spring.application.name=erdwithjpaproject
spring:
  application:
    name: erdwithjpaproject
  datasource:
    url: jdbc:postgresql://localhost:5432/jpaEntityDb
    username: postgres
    password: saimun
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080